// <auto-generated>
//   由 LearningPortfolioProfile「產生 C# Scheme」產生，請勿手改 —— 後台樣板改了請重新產生。
//   Project: 2026學習歷程使用範例 (01a11080-d25f-78c2-9d17-37f6c12bfdbd)
//   SchemeHash: fec576567eabfaee
//   要擴充請另開一個檔案寫 `partial class`。
// </auto-generated>
using EWova.LearningPortfolio;

using System;
using System.Collections.Generic;

public static partial class ProjectScheme
{
    /// <summary>LearningApp Id（= SDK Project.Id）</summary>
    public const string ProjectId = "01a11080-d25f-78c2-9d17-37f6c12bfdbd";
    /// <summary>產生時的後台樣板雜湊；與後端 /scheme 回的 Hash 不同代表樣板被改過，需要重新產生</summary>
    public const string SchemeHash = "fec576567eabfaee";

    /// <summary>
    /// 進度節點
    /// </summary>
    public enum ProgressNode
    {
        /// <summary>完成教材（clear）</summary>
        完成教材,
        /// <summary>登入開始探索教材！（clear/start）</summary>
        登入開始探索教材,
        /// <summary>第一關（clear/level1）</summary>
        第一關,
        /// <summary>體驗遊玩（clear/level1/play）</summary>
        第一關_體驗遊玩,
        /// <summary>考試測驗（clear/level1/test）</summary>
        第一關_考試測驗,
        /// <summary>第二關（clear/level2）</summary>
        第二關,
        /// <summary>測驗題（clear/level2/test）</summary>
        第二關_測驗題,
        /// <summary>綜合測驗（clear/sp）</summary>
        綜合測驗,
    }

    /// <summary>
    /// 進度節點對應的路徑
    /// </summary>
    public readonly static IReadOnlyDictionary<ProgressNode, string> ProgressNodeMap =
        new Dictionary<ProgressNode, string>()
        {
            [ProgressNode.完成教材] = "clear",
            [ProgressNode.登入開始探索教材] = "clear/start",
            [ProgressNode.第一關] = "clear/level1",
            [ProgressNode.第一關_體驗遊玩] = "clear/level1/play",
            [ProgressNode.第一關_考試測驗] = "clear/level1/test",
            [ProgressNode.第二關] = "clear/level2",
            [ProgressNode.第二關_測驗題] = "clear/level2/test",
            [ProgressNode.綜合測驗] = "clear/sp",
        };

    /// <summary>
    /// 頁面（值 = SDK Sheet.Pages[] 的 index）
    /// </summary>
    public enum Page
    {
        總覽 = 0,
        第一關 = 1,
        第二關 = 2,
        特殊測驗 = 3,
    }
    /// <summary>
    /// 關卡（總覽以外的頁面；值 = SDK Sheet.Pages[] 的 index）
    /// </summary>
    public enum Level
    {
        第一關 = 1,
        第二關 = 2,
        特殊測驗 = 3,
    }

    /// <summary>
    /// 關卡在總覽頁的列 index（後端依關卡順序填，第一個關卡在第 0 列）
    /// </summary>
    public readonly static IReadOnlyDictionary<Level, int> OverviewRowIndex =
        new Dictionary<Level, int>()
        {
            [Level.第一關] = 0,
            [Level.第二關] = 1,
            [Level.特殊測驗] = 2,
        };

    /// <summary>
    /// 總覽頁（每個關卡一列）
    /// </summary>
    public class OverviewPageLevelRow
    {
        /// <summary>關卡 — 唯讀</summary>
        [Column("關卡")] public string 關卡;
        /// <summary>分數</summary>
        [Column("分數")] public int 分數;
        /// <summary>總遊玩次數</summary>
        [Column("總遊玩次數")] public int 總遊玩次數;
        /// <summary>總遊玩時間（分鐘）</summary>
        [Column("總遊玩時間")] public int 總遊玩時間;
        /// <summary>最佳答題成績</summary>
        [Column("最佳答題成績")] public int 最佳答題成績;
    }

    /// <summary>
    /// 關卡頁面基底
    /// </summary>
    public abstract class LevelRowBase
    {
        public abstract Level Level { get; }
    }

    /// <summary>
    /// 第一關頁
    /// </summary>
    public class 第一關PageRow : LevelRowBase
    {
        public override Level Level => Level.第一關;
        /// <summary>分數</summary>
        [Column("分數")] public int 分數;
        /// <summary>遊玩日期</summary>
        [Column("遊玩日期")] public DateTimeOffset 遊玩日期;
        /// <summary>遊玩時長（分鐘）</summary>
        [Column("遊玩時長")] public int 遊玩時長;
        /// <summary>是否完成關卡</summary>
        [Column("是否完成關卡")] public bool 是否完成關卡;
        /// <summary>答題成績</summary>
        [Column("答題成績")] public int 答題成績;
    }

    /// <summary>
    /// 第二關頁
    /// </summary>
    public class 第二關PageRow : LevelRowBase
    {
        public override Level Level => Level.第二關;
        /// <summary>分數</summary>
        [Column("分數")] public int 分數;
        /// <summary>遊玩日期</summary>
        [Column("遊玩日期")] public DateTimeOffset 遊玩日期;
        /// <summary>遊玩時長（分鐘）</summary>
        [Column("遊玩時長")] public int 遊玩時長;
        /// <summary>是否完成關卡</summary>
        [Column("是否完成關卡")] public bool 是否完成關卡;
        /// <summary>答題成績</summary>
        [Column("答題成績")] public int 答題成績;
    }

    /// <summary>
    /// 特殊測驗頁
    /// </summary>
    public class 特殊測驗PageRow : LevelRowBase
    {
        public override Level Level => Level.特殊測驗;
        /// <summary>分數</summary>
        [Column("分數")] public int 分數;
        /// <summary>遊玩日期</summary>
        [Column("遊玩日期")] public DateTimeOffset 遊玩日期;
        /// <summary>遊玩時長（分鐘）</summary>
        [Column("遊玩時長")] public int 遊玩時長;
        /// <summary>是否完成關卡</summary>
        [Column("是否完成關卡")] public bool 是否完成關卡;
        /// <summary>答題成績</summary>
        [Column("答題成績")] public int 答題成績;
    }
}
