using Newtonsoft.Json;

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace EWova.LearningPortfolio.Editor
{
    #region Scheme JSON 模型（對應後端 GET /api/projects/{projectId}/scheme）

    [Serializable]
    public class ProjectSchemeJson
    {
        public int SchemeVersion;
        public string ProjectId;
        public string AppId;
        public string Name;
        public string Hash;
        public List<ProjectSchemePageJson> Pages = new();
        public List<ProjectSchemeProgressNodeJson> ProgressNodes = new();
    }

    [Serializable]
    public class ProjectSchemePageJson
    {
        public int Index;
        public string Key;
        public string Label;
        public bool IsOverview;
        public List<ProjectSchemeColumnJson> Columns = new();
    }

    [Serializable]
    public class ProjectSchemeColumnJson
    {
        public string Key;
        public string Label;
        public int SortOrder;
        public bool IsReadOnly;
        public string FieldType;
    }

    [Serializable]
    public class ProjectSchemeProgressNodeJson
    {
        public string Id;
        public string Label;
        public string Path;
        public List<string> AncestorLabels = new();
        public int Depth;
        public bool IsLeaf;
        public bool Hidden;
    }

    #endregion

    /// <summary>
    /// 把後台樣板 scheme 轉成 <c>ProjectScheme.cs</c>。純函式，不碰 Unity API，方便測試。
    /// </summary>
    public static class ProjectSchemeCodeGen
    {
        /// <summary>產生器看得懂的 scheme 格式版本上限</summary>
        public const int SupportedSchemeVersion = 1;

        public class Options
        {
            public string ClassName = "ProjectScheme";
            /// <summary>空字串 = 全域命名空間（與既有手寫版相同）</summary>
            public string Namespace = "";
        }

        public static string Generate(ProjectSchemeJson scheme, Options options)
        {
            if (scheme == null) throw new ArgumentNullException(nameof(scheme));
            if (scheme.SchemeVersion > SupportedSchemeVersion)
                throw new NotSupportedException(
                    $"Scheme 版本 {scheme.SchemeVersion} 比產生器支援的 {SupportedSchemeVersion} 新，請更新 LearningPortfolioSDK。");

            var w = new CodeWriter();
            var hasNamespace = !string.IsNullOrWhiteSpace(options.Namespace);

            w.Line("// <auto-generated>");
            w.Line("//   由 LearningPortfolioProfile「產生 C# Scheme」產生，請勿手改 —— 後台樣板改了請重新產生。");
            w.Line($"//   Project: {scheme.Name} ({scheme.ProjectId})");
            w.Line($"//   SchemeHash: {scheme.Hash}");
            w.Line("//   要擴充請另開一個檔案寫 `partial class`。");
            w.Line("// </auto-generated>");
            w.Line("using EWova.LearningPortfolio;");
            w.Line();
            w.Line("using System;");
            w.Line("using System.Collections.Generic;");
            w.Line();

            if (hasNamespace)
            {
                w.Line($"namespace {options.Namespace}");
                w.Open();
            }

            w.Line($"public static partial class {Identifier.Sanitize(options.ClassName, "ProjectScheme")}");
            w.Open();

            w.Line("/// <summary>LearningApp Id（= SDK Project.Id）</summary>");
            w.Line($"public const string ProjectId = {Literal(scheme.ProjectId)};");
            w.Line("/// <summary>產生時的後台樣板雜湊；與後端 /scheme 回的 Hash 不同代表樣板被改過，需要重新產生</summary>");
            w.Line($"public const string SchemeHash = {Literal(scheme.Hash)};");
            w.Line();

            WriteProgressNodes(w, scheme.ProgressNodes);
            var pageNames = WritePages(w, scheme.Pages);
            WriteRows(w, scheme.Pages, pageNames);

            w.Close();
            if (hasNamespace) w.Close();

            return w.ToString();
        }

        private static void WriteProgressNodes(CodeWriter w, List<ProjectSchemeProgressNodeJson> nodes)
        {
            // 命名規則沿用手寫版：根節點用自己的 label，其餘為「根以下的祖先 label + 自己」以底線串接
            // 例：完成教材 / 登入開始探索教材 / 第一關 / 第一關_體驗遊玩
            var names = new UniqueNames();
            var entries = nodes.Select(n =>
            {
                var parts = n.Depth == 0
                    ? new[] { n.Label }
                    : n.AncestorLabels.Skip(1).Append(n.Label);
                var raw = string.Join("_", parts.Select(p => Identifier.Sanitize(p, n.Id)));
                return (node: n, name: names.Take(Identifier.Sanitize(raw, n.Id)));
            }).ToList();

            w.Line("/// <summary>");
            w.Line("/// 進度節點");
            w.Line("/// </summary>");
            w.Line("public enum ProgressNode");
            w.Open();
            foreach (var (node, name) in entries)
            {
                w.Line($"/// <summary>{Xml(node.Label)}（{Xml(node.Path)}）{(node.Hidden ? " — 後台設為隱藏" : "")}</summary>");
                w.Line($"{name},");
            }
            w.Close();
            w.Line();

            w.Line("/// <summary>");
            w.Line("/// 進度節點對應的路徑");
            w.Line("/// </summary>");
            w.Line("public readonly static IReadOnlyDictionary<ProgressNode, string> ProgressNodeMap =");
            w.Indent();
            w.Line("new Dictionary<ProgressNode, string>()");
            w.Open();
            foreach (var (node, name) in entries)
                w.Line($"[ProgressNode.{name}] = {Literal(node.Path)},");
            w.Close("};");
            w.Outdent();
            w.Line();
        }

        private static Dictionary<int, string> WritePages(CodeWriter w, List<ProjectSchemePageJson> pages)
        {
            var names = new UniqueNames();
            var pageNames = pages.ToDictionary(p => p.Index, p => names.Take(Identifier.Sanitize(p.Label, $"Page{p.Index}")));

            w.Line("/// <summary>");
            w.Line("/// 頁面（值 = SDK Sheet.Pages[] 的 index）");
            w.Line("/// </summary>");
            w.Line("public enum Page");
            w.Open();
            foreach (var p in pages)
                w.Line($"{pageNames[p.Index]} = {p.Index},");
            w.Close();

            // Level = 總覽以外的頁面，值同樣是 Pages[] 的 index，可直接 Pages[(int)level]
            var levels = pages.Where(p => !p.IsOverview).ToList();
            w.Line("/// <summary>");
            w.Line("/// 關卡（總覽以外的頁面；值 = SDK Sheet.Pages[] 的 index）");
            w.Line("/// </summary>");
            w.Line("public enum Level");
            w.Open();
            foreach (var p in levels)
                w.Line($"{pageNames[p.Index]} = {p.Index},");
            w.Close();
            w.Line();

            var overview = pages.FirstOrDefault(p => p.IsOverview);
            if (overview != null)
            {
                // 後端刷新總覽頁時，第 i 列就是第 i 個關卡（0-based，不含總覽本身）
                w.Line("/// <summary>");
                w.Line("/// 關卡在總覽頁的列 index（後端依關卡順序填，第一個關卡在第 0 列）");
                w.Line("/// </summary>");
                w.Line("public readonly static IReadOnlyDictionary<Level, int> OverviewRowIndex =");
                w.Indent();
                w.Line("new Dictionary<Level, int>()");
                w.Open();
                for (int i = 0; i < levels.Count; i++)
                    w.Line($"[Level.{pageNames[levels[i].Index]}] = {i},");
                w.Close("};");
                w.Outdent();
                w.Line();
            }

            return pageNames;
        }

        private static void WriteRows(CodeWriter w, List<ProjectSchemePageJson> pages, Dictionary<int, string> pageNames)
        {
            var classNames = new UniqueNames();

            var overview = pages.FirstOrDefault(p => p.IsOverview);
            if (overview != null && overview.Columns.Count > 0)
            {
                w.Line("/// <summary>");
                w.Line($"/// {Xml(overview.Label)}頁（每個關卡一列）");
                w.Line("/// </summary>");
                w.Line($"public class {classNames.Take("OverviewPageLevelRow")}");
                w.Open();
                WriteColumns(w, overview.Columns);
                w.Close();
                w.Line();
            }

            w.Line("/// <summary>");
            w.Line("/// 關卡頁面基底");
            w.Line("/// </summary>");
            w.Line($"public abstract class {classNames.Take("LevelRowBase")}");
            w.Open();
            w.Line("public abstract Level Level { get; }");
            w.Close();

            foreach (var p in pages.Where(p => !p.IsOverview))
            {
                var levelName = pageNames[p.Index];
                w.Line();
                w.Line("/// <summary>");
                w.Line($"/// {Xml(p.Label)}頁");
                w.Line("/// </summary>");
                w.Line($"public class {classNames.Take(levelName + "PageRow")} : LevelRowBase");
                w.Open();
                w.Line($"public override Level Level => Level.{levelName};");
                WriteColumns(w, p.Columns);
                w.Close();
            }
        }

        private static void WriteColumns(CodeWriter w, List<ProjectSchemeColumnJson> columns)
        {
            // 欄位名不可與類別裡既有成員（Level）撞名
            var names = new UniqueNames("Level");
            foreach (var c in columns.OrderBy(c => c.SortOrder))
            {
                var (type, note) = MapFieldType(c.FieldType);
                var summary = Xml(c.Label) + (note != null ? $"（{note}）" : "") + (c.IsReadOnly ? " — 唯讀" : "");
                w.Line($"/// <summary>{summary}</summary>");
                w.Line($"[Column({Literal(c.Label)})] public {type} {names.Take(Identifier.Sanitize(c.Label, $"Column{c.SortOrder}"))};");
            }
        }

        /// <summary>
        /// 後端 FieldType → C# 型別。
        /// duration_* 刻意對到 int 而不是 TimeSpan：後端 / 後台把這些欄位當「秒數 / 分鐘數 / 毫秒數」的純數字，
        /// 而 SheetHelper 的 TimeSpan 會寫成 "00:05:00"，後台摘要算不出來、顯示也會變成原字串。
        /// </summary>
        internal static (string type, string note) MapFieldType(string fieldType)
        {
            switch ((fieldType ?? "").Trim().ToLowerInvariant())
            {
                case "number": return ("int", null);
                case "percentage": return ("float", "百分比數值，85 = 85%");
                case "boolean": return ("bool", null);
                case "duration_seconds": return ("int", "秒");
                case "duration_minutes": return ("int", "分鐘");
                case "duration_ms": return ("int", "毫秒");
                case "datetime_offset": return ("DateTimeOffset", null);
                case "string":
                default: return ("string", null);
            }
        }

        private static string Literal(string s) => JsonConvert.ToString(s ?? "");
        private static string Xml(string s) =>
            (s ?? "").Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("\r", " ").Replace("\n", " ");

        #region helpers

        private class UniqueNames
        {
            private readonly HashSet<string> _used;
            public UniqueNames(params string[] reserved) => _used = new HashSet<string>(reserved);

            public string Take(string name)
            {
                var candidate = name;
                for (int i = 2; !_used.Add(candidate); i++)
                    candidate = $"{name}_{i}";
                return candidate;
            }
        }

        internal static class Identifier
        {
            private static readonly HashSet<string> Keywords = new()
            {
                "abstract","as","base","bool","break","byte","case","catch","char","checked","class","const",
                "continue","decimal","default","delegate","do","double","else","enum","event","explicit","extern",
                "false","finally","fixed","float","for","foreach","goto","if","implicit","in","int","interface",
                "internal","is","lock","long","namespace","new","null","object","operator","out","override",
                "params","private","protected","public","readonly","ref","return","sbyte","sealed","short",
                "sizeof","stackalloc","static","string","struct","switch","this","throw","true","try","typeof",
                "uint","ulong","unchecked","unsafe","ushort","using","virtual","void","volatile","while",
            };

            /// <summary>
            /// label → 合法 C# 識別字。中文等 Unicode 字母本來就合法，直接保留（與手寫版一致）；
            /// 其他符號換成底線。
            /// </summary>
            public static string Sanitize(string raw, string fallback)
            {
                var sb = new StringBuilder();
                foreach (var ch in raw ?? "")
                {
                    var cat = char.GetUnicodeCategory(ch);
                    bool ok = char.IsLetterOrDigit(ch) || ch == '_'
                        || cat == UnicodeCategory.NonSpacingMark || cat == UnicodeCategory.SpacingCombiningMark
                        || cat == UnicodeCategory.ConnectorPunctuation;
                    sb.Append(ok ? ch : '_');
                }

                var s = Regex.Replace(sb.ToString(), "_+", "_").Trim('_');
                if (s.Length == 0)
                    s = fallback == null ? "_" : Sanitize(fallback, null);
                if (char.IsDigit(s[0]))
                    s = "_" + s;
                if (Keywords.Contains(s))
                    s = "@" + s;
                return s;
            }
        }

        private class CodeWriter
        {
            private readonly StringBuilder _sb = new();
            private int _indent;

            public void Line(string text = "")
            {
                if (text.Length > 0) _sb.Append(' ', _indent * 4).Append(text);
                _sb.Append('\n');
            }

            public void Indent() => _indent++;
            public void Outdent() => _indent--;
            public void Open() { Line("{"); _indent++; }
            public void Close(string closing = "}") { _indent--; Line(closing); }
            public override string ToString() => _sb.ToString();
        }

        #endregion
    }
}
